services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongo:27017/appointments?authSource=admin
  
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - PORT=3001
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

volumes:
  mongodb_data:
